modLoader="javafml" #mandatory
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Crimix/ServerTabInfo/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]] #mandatory
modId="servertabinfo"
authors="black_dog20"
displayURL="https://minecraft.curseforge.com/projects/server-tab-info"
version="${file.jarVersion}"
displayName="Server Tab Info"
updateJSONURL="https://raw.githubusercontent.com/Crimix/ServerTabInfo/master/update.json"
logoFile="servertabinfo-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
description='''
Server Tab Info is a small server utility mod that displays mean tick time and tps information on a nice elegant way.
The inspiration came from a small feature from MineTogether which used to work quite nice for me, but lately failed to work, therefore I create this mod.
'''

[[dependencies.servertabinfo]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.servertabinfo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"